# Generated by Django 2.0.3 on 2019-12-27 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='GPX_files')),
                ('file_name', models.TextField(blank=True, default='')),
                ('uploaded_at', models.TimeField(default=django.utils.timezone.now)),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_15_minutes', models.IntegerField()),
                ('per_day', models.IntegerField()),
            ],
        ),
    ]
